server:
  port: 8000

eureka:
  client:
    register-with-eureka: true  # Service A will register itself with Eureka
    fetch-registry: true  # Service A will fetch the registry of other services from Eureka
    service-url:
      defaultZone: http://localhost:5000/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true


info:
  app:
    name: Employee App
    description: Employee microservice application
    version: 1.0.0

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices_selenium_express  # Default: "jdbc:mysql://localhost:3306/mydb"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Default Hibernate strategy
    show-sql: true

address-service:
  base-url: http://localhost:9000/app/address