server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/

  #      z1: http://localhost:5000/eureka/
  #      z2: http://localhost:5001/eureka/
  #      z3: http://localhost:5002/eureka/

  instance:
    metadata-map:
      configPath: /app/address/
      user: Rahul  #Not required (key, value pair)
      password: xxxx #Not required


#      z1: http://localhost:5000/eureka/
#      z2: http://localhost:5001/eureka/
#      z3: http://localhost:5002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: Address App
    description: Address microservice application
    version: 1.0.0

spring:
  application:
    name: address-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservices_selenium_express  # Default: "jdbc:mysql://localhost:3306/mydb"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Default Hibernate strategy
    show-sql: true
address-service:
  base-url: http://localhost:8000/app/address